name: blu_ray_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.5
  http: ^1.2.2
  csv: ^6.0.0
  logger: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  blu_ray_shared:
    path: ../blu-ray-shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
